[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
opacity = 0.8
padding = { x = 5, y = 5 }

[general]
import = ["./themes/themes/tokyonight.toml"]
